apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app
    author: Tawfeeq
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      labels:
        name: result-app
    spec:
      containers:
        - name: result
          image: tawfeeq421/result-app
          ports:
            - containerPort: 80
