apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-service
spec:
  type: LoadBalancer
  port:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app

